### ISSUE TITLE
Recebimento de dados da variável do Switch case

### ISSUE THREAD

**Issue by rainarodrigues** [talesvalente/Apple-Developer-Academy#10]
### Oie Tales, adorei seu código! Minha sugestão é que você diminua as possibilidades do recebimento da variável do switch case de acordo com as opções do menu.   

https://github.com/talesvalente/Apple-Developer-Academy/blob/cca42072b5a04aaea694e9058ad9472adc7588a0/Trabalhos%20em%20Equipe/CLB%20-%20Swift/CBL-PROJECT/main/main.swift#L37

### Aqui está um  exemplo que como você pode fazer minha sugestão: 

```
var teste = readLine()
        while true {
            if (Int(teste!) == nil) || (Int(teste!)! >= 5) || (Int(teste!)! <= 0) {
                print ("Valor invalido, digite de 1 a 5 pra acessar o valor de opcão: \n")
                teste = readLine()
            }else{
                break
            }
```

**Comment by talesvalente** [comment]
Sugestão válida porém foge do que queremos oferecer ao usuário.

Para evitar que o nosso programa finalize sempre que o usuário inserir um dado erro, foi criado um lanço de repetição infinito que irá checar as entradas do usuário sempre que ele digitar e der enter.  Dessa forma, tornamos o programa "menos chato" de se operar.

Seu código é válido, porém, se implementarmos isso o usuário vai ter que abrir o programa e começar tudo de novo sempre que digitar algo que não deveria.
