### ISSUE TITLE
Sugestão.

### ISSUE THREAD

**Issue by Luizerz** [talesvalente/Apple-Developer-Academy#12]
### Primeiramente parabéns pelo programa, a estrutura tá bem legível e bem estruturado, uma sugestão que posso dar é substituir esses vários print por um só com uma estrutra maior.  

https://github.com/talesvalente/Apple-Developer-Academy/blob/ab1873651734eca2e97ae54ade9e3b09dce150f4/Trabalhos%20em%20Equipe/CLB%20-%20Swift/CBL-PROJECT/src/VALENTE/iValente.swift#L135-L153  
### É possível usar o seguinte:  
```
let texto = “””
Valor que você deseja receber: \(valorReceber!)
Bandeira do cartão do cliente \(bandeira!)
“””
Print(texto)
```   
### No mais, parabéns pelo programa, adorei poder ter o preço sugerido para meu item.

**Comment by talesvalente** [comment]
Perfeito, @Luizerz ! Contudo, preciso compartilhar a experiencia que tive ao implementar seu código... Fiz o teste da sua proposta no xcode e o código aumento o tempo de compilação e uso de memória... Foi algo quase que imperceptível mas aumentou querendo ou não. 

Para códigos maiores ou projetos profissionais, essa abordagem é considerada ineficiente e fortemente desencorajada. A utilização dos prints neste contexto foi pra facilitar o entendimento e deixar o CLI mais atrativo aos olhos.

Seu feedback foi válido e bastante importante pois nos mostra que existem "mil e uma maneiras de se preparar o nestom", ou seja, várias formas de se resolver um mesmo problema. Porém, não iremos aplicar por não haver ganhos de perfomance ou estabilidade significativos nesta aplicação.
